# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'GitIssuesExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitIssuesExample

  # Architecture
	pod 'ReactorKit'
	
	# Reactive
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'RxDataSources'
	pod 'RxViewController'
	pod 'RxOptional'
	pod 'RxSwiftExt'
	pod 'ReusableKit'

  # UI
  pod 'SnapKit'
	pod 'Then'

end
